name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Service1
        uses: docker/build-push-action@v4
        with:
          context: ./service1/Dockerfile
          push: true
          tags: poco349/service1:latest

      - name: Build & Push Service2
        uses: docker/build-push-action@v4
        with:
          context: ./service2/Dockerfile
          push: true
          tags: poco349/service2:latest
